# Generated by Django 6.0 on 2025-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=100),
        ),
    ]
